---
title: "Venn Diagrams for 3 species OGs comparison using FindMarker of Seurat"
output:
  html_document: default
  pdf_document: default
date: '2022-08-04'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Clean ortholog find
orthofinder = read.csv("/Users/tranchau/Documents/SC_crossSpecies/OrthoFinder_source/Ath_maize_tom_rice/OrthoFinder/Results_Aug04/Orthogroups/Orthogroups.tsv", header = TRUE, sep = "\t")

library(tidyr)
library(dplyr)
library("stringr") 

og_ath = orthofinder[,c("Orthogroup", "Arabidopsis")] %>%
  mutate(Arabidopsis = strsplit(as.character(Arabidopsis), ",")) %>% # Split long string in a row into multiple rows
  unnest(Arabidopsis) %>%
  mutate(Arabidopsis = str_extract(Arabidopsis, "[^.]+"))  %>% # Extract all character before the first dot
  mutate(across(where(is.character), str_trim)) %>%  # Remove white spaces
  distinct(Arabidopsis, .keep_all = TRUE)  # Remove duplicated rows based on Arabidopsis column
  #remove_rownames %>% column_to_rownames(var="Arabidopsis")


og_maize = orthofinder[,c("Orthogroup", "Zeamays")] %>%
  mutate(Zeamays = strsplit(as.character(Zeamays), ",")) %>% # Split long string in a row into multiple rows
  unnest(Zeamays) %>%
  mutate(Zeamays = str_extract(Zeamays, "[^_]+")) %>% # Extract all character before the first underscore
  mutate(across(where(is.character), str_trim)) %>% # Remove white spaces
  distinct(Zeamays, .keep_all = TRUE)  # Remove duplicated rows based on Zeamays column
  #remove_rownames %>% column_to_rownames(var="Zeamays")

og_oryza = orthofinder[,c("Orthogroup", "Oryza")] %>%
  mutate(Oryza = strsplit(as.character(Oryza), ",")) %>% # Split long string in a row into multiple rows
  unnest(Oryza) %>%
  mutate(Oryza = str_extract(Oryza, "[^-]+")) %>% # Extract all character before the first underscore
  mutate(across(where(is.character), str_trim)) %>% # Remove white spaces
  distinct(Oryza, .keep_all = TRUE)  %>% # Remove duplicated rows based on Oryza column
  mutate(across('Oryza', str_replace, 't', 'g'))
og_oryza

```

```{r}
# Load Marker Genes
library(Seurat); library(Matrix); library(tidyverse)

#---------------------------------------
MG_ara = readRDS("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Data/MG_092522_Ath_05.RData")
print("Number of marker genes per cell types")
table(MG_ara$cluster)

#---------------------------------------
MG_maize = readRDS("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Data/MG_092522_Maize_05.RData")
print("Number of marker genes per cell types")
table(MG_maize$cluster)

#---------------------------------------
MG_oryza = readRDS("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Data/MG_092522_Rice_05.RData")
print("Number of marker genes per cell types")
table(MG_oryza$cluster)
```

```{r}
# Merge marker gene and OG gene table
# Arabidopsis #######################
Ath_MG_OG = merge(MG_ara, og_ath, by.x = "gene", by.y = "Arabidopsis") %>% arrange(cluster, desc(avg_log2FC)) %>% select("gene", "Orthogroup", "cluster", "avg_log2FC") %>% group_by(cluster) %>% top_n(200)
length(unique(Ath_MG_OG[Ath_MG_OG$cluster == "Stele1",]$Orthogroup))

# Maize #############################
Maize_MG_OG = merge(MG_maize, og_maize, by.x = "gene", by.y = "Zeamays") %>% arrange( cluster, desc(avg_log2FC)) %>% select("gene", "Orthogroup", "cluster", "avg_log2FC") %>% group_by(cluster) %>% top_n(200)
length(unique(Maize_MG_OG[Maize_MG_OG$cluster == "Endodermal_Initials",]$Orthogroup))

# Oryza #############################
Oryza_MG_OG = merge(MG_oryza, og_oryza, by.x = "gene", by.y = "Oryza") %>% arrange( cluster, desc(avg_log2FC)) %>% select("gene", "Orthogroup", "cluster", "avg_log2FC") %>% group_by(cluster) %>% top_n(200)
length(unique(Oryza_MG_OG[Oryza_MG_OG$cluster == "Endodermis",]$Orthogroup))


length(intersect(intersect(Ath_MG_OG[Ath_MG_OG$cluster == "Stele1",]$Orthogroup, Maize_MG_OG[Maize_MG_OG$cluster == "Endodermal_Initials",]$Orthogroup), Oryza_MG_OG[Oryza_MG_OG$cluster == "Endodermis",]$Orthogroup))

length(unique(Ath_MG_OG[Ath_MG_OG$cluster == "Stele1",]$Orthogroup))
length(unique(Maize_MG_OG[Maize_MG_OG$cluster == "Endodermal_Initials",]$Orthogroup))
length(unique(Oryza_MG_OG[Oryza_MG_OG$cluster == "Endodermis",]$Orthogroup))
```


```{r}
# https://cran.r-project.org/web/packages/ggVennDiagram/vignettes/using-new-shapes.html
## Function create table of common OG gene names between 2 species
library(ggVennDiagram)
library(ggplot2)


length(unique(Ath_MG_OG[Ath_MG_OG$cluster == "Cortex",]$Orthogroup))
length(unique(Maize_MG_OG[Maize_MG_OG$cluster == "Cortex",]$Orthogroup))
length(unique(Oryza_MG_OG[Oryza_MG_OG$cluster == "Cortex",]$Orthogroup))


# List of items
cortex <- list(A = unique(Oryza_MG_OG[Oryza_MG_OG$cluster == "Cortex",]$Orthogroup), 
               B = unique(Maize_MG_OG[Maize_MG_OG$cluster == "Cortex",]$Orthogroup),
               C = unique(Ath_MG_OG[Ath_MG_OG$cluster == "Cortex",]$Orthogroup)
               )

# Extract data for other purpose
OG_Seurat_cortex = intersect(intersect(unique(Oryza_MG_OG[Oryza_MG_OG$cluster == "Cortex",]$Orthogroup), unique(Maize_MG_OG[Maize_MG_OG$cluster == "Cortex",]$Orthogroup)), unique(Ath_MG_OG[Ath_MG_OG$cluster == "Cortex",]$Orthogroup))
#saveRDS(OG_Seurat_cortex, "OG_Seurat_cortex.RData")

#----------------------------
venn = Venn(cortex)
data = process_data(venn, shape_id == "301f")

cortex_plot = ggplot() +
  #ggtitle("Cotex: 185, 179, 174") +  
  ggtitle("Cotex") +  
  geom_sf(aes(fill = count), data = venn_region(data)) +
  geom_sf(color = c("purple2","tomato3","orange2"), size = 1, data = venn_setedge(data), show.legend = FALSE) +
  #coord_sf(xlim = c(0, 900), ylim = c(0, 900)) + 
  geom_sf_text(label = c("Oryza", "Zeamays", "Arabidopsis"), size = 6, color = c("purple2","tomato3","orange2"), fontface= "bold", data = venn_setlabel(data)) +
  geom_sf_label(aes(label = count), data = venn_region(data), size = 5) +
  scale_fill_gradient(low="white",high = "green3") +
  theme_void() +
  theme(legend.position="right", 
                  #axis.line.x = element_line(size = 1),
                  #axis.line.y = element_line(size = 1),
                  #axis.text.x = element_text(color="black", face = "bold",size=12, angle=60, vjust = 0.8, hjust = 0.5), 
                  #axis.text.y = element_text(color="black", face = "bold",size=20, angle=0, vjust = 0.5, hjust = 0.5),
                  #axis.ticks.length = unit(0.3,"cm"),
                  #axis.ticks = element_line(size = 2),
                  legend.title = element_text(size=12),
                  legend.text = element_text(size=10),
                  plot.title = element_text(size=18, face= "bold", colour= "black", hjust = 0.5),
                  #axis.title.x = element_text(size=18, face="bold", colour = "purple3", vjust = 2),    
                  #axis.title.y = element_text(size=18, face="bold", colour = "purple3")
        )  


#pdf("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Figure/Figure2_SeuratComparison/Cortex_Vendiagram.pdf", width = 7, height = 5)
cortex_plot
#dev.off()
```


```{r}
library(ggVennDiagram)
library(ggplot2)

# List of items
xylem <- list(A = unique(Oryza_MG_OG[Oryza_MG_OG$cluster == "Xylem",]$Orthogroup), 
              B = unique(Maize_MG_OG[Maize_MG_OG$cluster == "Xylem",]$Orthogroup),
              C = unique(Ath_MG_OG[Ath_MG_OG$cluster == "Xylem",]$Orthogroup)
        )

#----------------------------
# Extract data for other steps
OG_Seurat_xylem = intersect(unique(Ath_MG_OG[Ath_MG_OG$cluster == "Xylem",]$Orthogroup),intersect(unique(Oryza_MG_OG[Oryza_MG_OG$cluster == "Xylem",]$Orthogroup), unique(Maize_MG_OG[Maize_MG_OG$cluster == "Xylem",]$Orthogroup)))
#saveRDS(OG_Seurat_xylem, "OG_Seurat_xylem.RData")

#----------------------------
venn = Venn(xylem)
data = process_data(venn, shape_id == "301f")

xylem_plot = ggplot() +
  #ggtitle("Xylem: 190, 193, 177") +  
  ggtitle("Xylem") +  
  geom_sf(aes(fill = count), data = venn_region(data)) +
  geom_sf(color = c("purple2","tomato3","orange2"), size = 1, data = venn_setedge(data), show.legend = FALSE) +
  geom_sf_text(label = c("Oryza", "Zeamays", "Arabidopsis"), size = 6, color = c("purple2","tomato3","orange2"), fontface= "bold", data = venn_setlabel(data)) +
  geom_sf_label(aes(label = count), data = venn_region(data), size = 5) +
  scale_fill_gradient(low="white",high = "#FDE725CC") +
  theme_void() +
  theme(legend.position="right", 
                  legend.title = element_text(size=12),
                  legend.text = element_text(size=10),
                  plot.title = element_text(size=18, face= "bold", colour= "black", hjust = 0.5)
        )  

#pdf("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Figure/Figure2_SeuratComparison/Xylem_Vendiagram.pdf", width = 7, height = 5)
xylem_plot
#dev.off()
```



```{r}
library(ggVennDiagram)
library(ggplot2)

# List of items
mix <- list(A = unique(Oryza_MG_OG[Oryza_MG_OG$cluster == "Endodermis",]$Orthogroup), 
              B = unique(Maize_MG_OG[Maize_MG_OG$cluster == "Endodermal_Initials",]$Orthogroup),
              C = unique(Ath_MG_OG[Ath_MG_OG$cluster == "Stele1",]$Orthogroup)
        )
# Extract mix OG markers
OG_Seurat_mix = intersect(intersect(unique(Oryza_MG_OG[Oryza_MG_OG$cluster == "Endodermis",]$Orthogroup), unique(Maize_MG_OG[Maize_MG_OG$cluster == "Endodermal_Initials",]$Orthogroup)), unique(Ath_MG_OG[Ath_MG_OG$cluster == "Stele1",]$Orthogroup))
#saveRDS(OG_Seurat_mix, "OG_Seurat_MRendodermis_ATHstele.RData")
#--------------------------------------------------------------

venn = Venn(mix)
data = process_data(venn, shape_id == "301f")

mix_plot = ggplot() +
  ggtitle("OryzaEndodermis_MaizeEndodermis_ATHStele1: 139, 159, 171") +  
  ggtitle("Oryza-MaizeEndo_ATHStele") +  
  geom_sf(aes(fill = count), data = venn_region(data)) +
  geom_sf(color = c("purple2","tomato3","orange2"), size = 1, data = venn_setedge(data), show.legend = FALSE) +
  geom_sf_text(label = c("Oryza", "Zeamays", "Arabidopsis"), size = 6, color = c("purple2","tomato3","orange2"), fontface= "bold", data = venn_setlabel(data)) +
  geom_sf_label(aes(label = count), data = venn_region(data), size = 5) +
  scale_fill_gradient(low="white",high = "#277F8ECF") +
  theme_void() +
  theme(legend.position="right", 
                  #axis.line.x = element_line(size = 1),
                  #axis.line.y = element_line(size = 1),
                  #axis.text.x = element_text(color="black", face = "bold",size=12, angle=60, vjust = 0.8, hjust = 0.5), 
                  #axis.text.y = element_text(color="black", face = "bold",size=20, angle=0, vjust = 0.5, hjust = 0.5),
                  #axis.ticks.length = unit(0.3,"cm"),
                  #axis.ticks = element_line(size = 2),
                  legend.title = element_text(size=12),
                  legend.text = element_text(size=10),
                  plot.title = element_text(size=18, face= "bold", colour= "black", hjust = 0.5),
                  #axis.title.x = element_text(size=18, face="bold", colour = "purple3", vjust = 2),    
                  #axis.title.y = element_text(size=18, face="bold", colour = "purple3")
        )  

#pdf("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Figure/Figure2_SeuratComparison/ATHStele1_MaizeEndodermal_OryzaEndodermis_Vendiagram.pdf", width = 7, height = 5)
mix_plot
#dev.off()
```





```{r}
library(ggVennDiagram)
library(ggplot2)

length(unique(Oryza_MG_OG[Oryza_MG_OG$cluster == "Trichoblast1",]$Orthogroup))
length(unique(Maize_MG_OG[Maize_MG_OG$cluster == "Epidermis",]$Orthogroup))
length(unique(Ath_MG_OG[Ath_MG_OG$cluster == "Trichoblast2",]$Orthogroup))
# List of items
hair <- list(A = unique(Oryza_MG_OG[Oryza_MG_OG$cluster == "Trichoblast1",]$Orthogroup), 
             B = unique(Maize_MG_OG[Maize_MG_OG$cluster == "Epidermis",]$Orthogroup),
             C = unique(Ath_MG_OG[Ath_MG_OG$cluster == "Trichoblast2",]$Orthogroup)
        )


#----------------------------
# Extract common hair data
OG_Seurat_trichoblast = intersect(intersect(unique(Oryza_MG_OG[Oryza_MG_OG$cluster == "Trichoblast1",]$Orthogroup), unique(Maize_MG_OG[Maize_MG_OG$cluster == "Epidermis",]$Orthogroup)), unique(Ath_MG_OG[Ath_MG_OG$cluster == "Trichoblast2",]$Orthogroup))
#saveRDS(OG_Seurat_trichoblast, "OG_Seurat_trichoblast.RData")
#----------------------------

#----------------------------
venn = Venn(hair)
data = process_data(venn, shape_id == "301f")

hair_plot = ggplot() +
  #ggtitle("Trichoblast: 191, 155, 182") +  
  ggtitle("Trichoblast") + 
  geom_sf(aes(fill = count), data = venn_region(data)) +
  geom_sf(color = c("purple2","tomato3","orange2"), size = 1, data = venn_setedge(data), show.legend = FALSE) +
  geom_sf_text(label = c("Oryza", "Zeamays", "Arabidopsis"), size = 6, color = c("purple2","tomato3","orange2"), fontface= "bold", data = venn_setlabel(data)) +
  geom_sf_label(aes(label = count), data = venn_region(data), size = 5) +
  scale_fill_gradient(low="white",high = "#5AC863D7") +
  theme_void() +
  theme(legend.position="right", 
                  #axis.line.x = element_line(size = 1),
                  #axis.line.y = element_line(size = 1),
                  #axis.text.x = element_text(color="black", face = "bold",size=12, angle=60, vjust = 0.8, hjust = 0.5), 
                  #axis.text.y = element_text(color="black", face = "bold",size=20, angle=0, vjust = 0.5, hjust = 0.5),
                  #axis.ticks.length = unit(0.3,"cm"),
                  #axis.ticks = element_line(size = 2),
                  legend.title = element_text(size=12),
                  legend.text = element_text(size=10),
                  plot.title = element_text(size=18, face= "bold", colour= "black", hjust = 0.5),
                  #axis.title.x = element_text(size=18, face="bold", colour = "purple3", vjust = 2),    
                  #axis.title.y = element_text(size=18, face="bold", colour = "purple3")
        )  

#pdf("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Figure/Figure2_SeuratComparison/Trichoblast_Vendiagram.pdf", width = 7, height = 5)
hair_plot
#dev.off()
```


```{r}
library(ggVennDiagram)
library(ggplot2)

# List of items
nonhair <- list(A = unique(Oryza_MG_OG[Oryza_MG_OG$cluster == "Atrichoblast",]$Orthogroup), 
              B = unique(Maize_MG_OG[Maize_MG_OG$cluster == "Epidermis",]$Orthogroup),
              C = unique(Ath_MG_OG[Ath_MG_OG$cluster == "Atrichoblast1",]$Orthogroup)
        )
#----------------------------
# Extract nonhair dat
OG_Seurat_atrichoblast = intersect(intersect(unique(Oryza_MG_OG[Oryza_MG_OG$cluster == "Atrichoblast",]$Orthogroup), unique(Maize_MG_OG[Maize_MG_OG$cluster == "Epidermis",]$Orthogroup)),  unique(Ath_MG_OG[Ath_MG_OG$cluster == "Atrichoblast1",]$Orthogroup))
#saveRDS(OG_Seurat_atrichoblast, "OG_Seurat_atrichoblast.RData")
#----------------------------


#----------------------------
venn = Venn(nonhair)
data = process_data(venn, shape_id == "301f")

nonhair_plot = ggplot() +
  #ggtitle("Atrichoblast:  186, 155, 186") +  
  ggtitle("Atrichoblast") +  
  geom_sf(aes(fill = count), data = venn_region(data)) +
  geom_sf(color = c("purple2","tomato3","orange2"), size = 1, data = venn_setedge(data), show.legend = FALSE) +
  geom_sf_text(label = c("Oryza", "Zeamays", "Arabidopsis"), size = 6, color = c("purple2","tomato3","orange2"), fontface= "bold", data = venn_setlabel(data)) +
  geom_sf_label(aes(label = count), data = venn_region(data), size = 5) +
  scale_fill_gradient(low="white",high = "#1F9D90D8") +
  theme_void() +
  theme(legend.position="right", 
                  #axis.line.x = element_line(size = 1),
                  #axis.line.y = element_line(size = 1),
                  #axis.text.x = element_text(color="black", face = "bold",size=12, angle=60, vjust = 0.8, hjust = 0.5), 
                  #axis.text.y = element_text(color="black", face = "bold",size=20, angle=0, vjust = 0.5, hjust = 0.5),
                  #axis.ticks.length = unit(0.3,"cm"),
                  #axis.ticks = element_line(size = 2),
                  legend.title = element_text(size=12),
                  legend.text = element_text(size=10),
                  plot.title = element_text(size=18, face= "bold", colour= "black", hjust = 0.5),
                  #axis.title.x = element_text(size=18, face="bold", colour = "purple3", vjust = 2),    
                  #axis.title.y = element_text(size=18, face="bold", colour = "purple3")
        )  

#pdf("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Figure/Figure2_SeuratComparison/Atrichoblast_Vendiagram.pdf", width = 7, height = 5)
nonhair_plot
#dev.off()
```


```{r}
library(ggVennDiagram)
library(ggplot2)

length(unique(Oryza_MG_OG[Oryza_MG_OG$cluster == "Endodermis",]$Orthogroup))
length(unique(Maize_MG_OG[Maize_MG_OG$cluster == "Endodermal_Initials",]$Orthogroup))
length(unique(Ath_MG_OG[Ath_MG_OG$cluster == "Atrichoblast2",]$Orthogroup))

# List of items
mix2 <- list(A = unique(Oryza_MG_OG[Oryza_MG_OG$cluster == "Endodermis",]$Orthogroup), 
              B = unique(Maize_MG_OG[Maize_MG_OG$cluster == "Endodermal_Initials",]$Orthogroup),
              C = unique(Ath_MG_OG[Ath_MG_OG$cluster == "Atrichoblast2",]$Orthogroup)
        )

#----------------------------
OG_Seurat_MRendodermis_ATHnonhair = intersect(intersect(unique(Oryza_MG_OG[Oryza_MG_OG$cluster == "Endodermis",]$Orthogroup), unique(Maize_MG_OG[Maize_MG_OG$cluster == "Endodermal_Initials",]$Orthogroup)), unique(Ath_MG_OG[Ath_MG_OG$cluster == "Atrichoblast2",]$Orthogroup))
#saveRDS(OG_Seurat_MRendodermis_ATHnonhair, "OG_Seurat_MRendodermis_ATHnonhair.RData")
#----------------------------

#----------------------------
venn = Venn(mix2)
data = process_data(venn, shape_id == "301f")

mix2_plot = ggplot() +
  #ggtitle("Endo (R&M) and Nonhair (ATH): 139, 159, 119") +  
  ggtitle("Oryza-MaizeEndo_ATHNonhair") +  
  geom_sf(aes(fill = count), data = venn_region(data)) +
  geom_sf(color = c("purple2","tomato3","orange2"), size = 1, data = venn_setedge(data), show.legend = FALSE) +
  geom_sf_text(label = c("Oryza", "Zeamays", "Arabidopsis"), size = 6, color = c("purple2","tomato3","orange2"), fontface= "bold", data = venn_setlabel(data)) +
  geom_sf_label(aes(label = count), data = venn_region(data), size = 5) +
  scale_fill_gradient(low="white",high =  "#365C8DC7") +
  theme_void() +
  theme(legend.position="right", 
                  #axis.line.x = element_line(size = 1),
                  #axis.line.y = element_line(size = 1),
                  #axis.text.x = element_text(color="black", face = "bold",size=12, angle=60, vjust = 0.8, hjust = 0.5), 
                  #axis.text.y = element_text(color="black", face = "bold",size=20, angle=0, vjust = 0.5, hjust = 0.5),
                  #axis.ticks.length = unit(0.3,"cm"),
                  #axis.ticks = element_line(size = 2),
                  legend.title = element_text(size=12),
                  legend.text = element_text(size=10),
                  plot.title = element_text(size=18, face= "bold", colour= "black", hjust = 0.5),
                  #axis.title.x = element_text(size=18, face="bold", colour = "purple3", vjust = 2),    
                  #axis.title.y = element_text(size=18, face="bold", colour = "purple3")
        )  



#pdf("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Figure/Figure2_SeuratComparison/Oryza_MaizeEndodermis_ATHAtrichoblast_Vendiagram.pdf", width = 7, height = 5)
mix2_plot
#dev.off()
```



