---
title: "Common OMG comparison among three plant species by SHAP"
output: html_document
date: '2022-09-02'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Clean ortholog find
orthofinder = read.csv("/Users/tranchau/Documents/SC_crossSpecies/OrthoFinder_source/Ath_maize_tom_rice/OrthoFinder/Results_Aug04/Orthogroups/Orthogroups.tsv", header = TRUE, sep = "\t")

library(tidyr)
library(dplyr)
library("stringr") 

og_ath = orthofinder[,c("Orthogroup", "Arabidopsis")] %>%
  mutate(Arabidopsis = strsplit(as.character(Arabidopsis), ",")) %>% # Split long string in a row into multiple rows
  unnest(Arabidopsis) %>%
  mutate(Arabidopsis = str_extract(Arabidopsis, "[^.]+"))  %>% # Extract all character before the first dot
  mutate(across(where(is.character), str_trim)) %>%  # Remove white spaces
  distinct(Arabidopsis, .keep_all = TRUE)  # Remove duplicated rows based on Arabidopsis column
  #remove_rownames %>% column_to_rownames(var="Arabidopsis")


og_maize = orthofinder[,c("Orthogroup", "Zeamays")] %>%
  mutate(Zeamays = strsplit(as.character(Zeamays), ",")) %>% # Split long string in a row into multiple rows
  unnest(Zeamays) %>%
  mutate(Zeamays = str_extract(Zeamays, "[^_]+")) %>% # Extract all character before the first underscore
  mutate(across(where(is.character), str_trim)) %>% # Remove white spaces
  distinct(Zeamays, .keep_all = TRUE)  # Remove duplicated rows based on Zeamays column
  #remove_rownames %>% column_to_rownames(var="Zeamays")

og_oryza = orthofinder[,c("Orthogroup", "Oryza")] %>%
  mutate(Oryza = strsplit(as.character(Oryza), ",")) %>% # Split long string in a row into multiple rows
  unnest(Oryza) %>%
  mutate(Oryza = str_extract(Oryza, "[^-]+")) %>% # Extract all character before the first underscore
  mutate(across(where(is.character), str_trim)) %>% # Remove white spaces
  distinct(Oryza, .keep_all = TRUE)  %>% # Remove duplicated rows based on Oryza column
  mutate(across('Oryza', str_replace, 't', 'g'))
og_oryza

```



```{r}
ATH_marker = read.table("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Data_SPMarker/111022_ATH_out/opt_SHAP_markers_dir/opt_all_novel_marker.txt")
ATH_marker = ATH_marker[-which(ATH_marker$V1 == "feature"),]
ATH_marker$V4 = as.numeric(ATH_marker$V4)

Maize_marker = read.table("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Data_SPMarker/111022_Maize_out/opt_SHAP_markers_dir/opt_all_novel_marker.txt")
Maize_marker = Maize_marker[-which(Maize_marker$V1 == "feature"),]
Maize_marker$V4 = as.numeric(Maize_marker$V4)

Rice_marker = read.table("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Data_SPMarker/111022_Rice_out/opt_SHAP_markers_dir/opt_all_novel_marker.txt")
Rice_marker = Rice_marker[-which(Rice_marker$V1== "feature"),]
Rice_marker$V4 = as.numeric(Rice_marker$V4)


ATH_comOG = merge(ATH_marker, og_ath, by.x = "V1", by.y = "Arabidopsis") %>% arrange(V2, desc(V4)) %>% group_by(V2) %>% slice(1:200)

Maize_comOG = merge(Maize_marker, og_maize, by.x = "V1", by.y = "Zeamays") %>% arrange(V2, desc(V4)) %>% group_by(V2) %>% slice(1:200)

Rice_comOG = merge(Rice_marker, og_oryza, by.x = "V1", by.y = "Oryza") %>% arrange(V2, desc(V4)) %>% group_by(V2) %>% slice(1:200)
```



```{r}
# https://cran.r-project.org/web/packages/ggVennDiagram/vignettes/using-new-shapes.html
## Function create table of common OG gene names between 2 species
library(ggVennDiagram)
library(ggplot2)

# List of items
xylem <- list(A = unique(Rice_comOG[Rice_comOG$V2 == "Xylem",]$Orthogroup), 
              B = unique(Maize_comOG[Maize_comOG$V2 == "Xylem",]$Orthogroup),
              C = unique(ATH_comOG[ATH_comOG$V2 == "Xylem",]$Orthogroup)
        )

##
com = intersect(intersect(unique(Rice_comOG[Rice_comOG$V2 == "Xylem",]$Orthogroup), unique(Maize_comOG[Maize_comOG$V2 == "Xylem",]$Orthogroup)), unique(ATH_comOG[ATH_comOG$V2 == "Xylem",]$Orthogroup))
saveRDS(com, "/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Data/SHAP_OG_102322_Xylem.RData")
##

#----------------------------
venn = Venn(xylem)
data = process_data(venn, shape_id == "301f")

xylem_plot = ggplot() +
  ggtitle("Xylem") +  
  geom_sf(aes(fill = count), data = venn_region(data)) +
  geom_sf(color = c("purple2","tomato3","orange2"), size = 1, data = venn_setedge(data), show.legend = FALSE) +
  geom_sf_text(label = c("Oryza", "Zeamays", "Arabidopsis"), size = 6, color = c("purple2","tomato3","orange2"), fontface= "bold", data = venn_setlabel(data)) +
  geom_sf_label(aes(label = count), data = venn_region(data), size = 5) +
  scale_fill_gradient(low="white",high = "#FDE725CC") +
  theme_void() +
  theme(legend.position="right", 
                  legend.title = element_text(size=12),
                  legend.text = element_text(size=10),
                  plot.title = element_text(size=18, face= "bold", colour= "black", hjust = 0.5),
        )  


#pdf("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Figure/Figure3_SHAP_comparison/SHAP_Venn_Xylem.pdf", width = 7, height = 5)
xylem_plot
#dev.off()

```


```{r}
library(ggVennDiagram)
library(ggplot2)

# List of items
cortex <- list(A = unique(Rice_comOG[Rice_comOG$V2 == "Cortex",]$Orthogroup), 
              B = unique(Maize_comOG[Maize_comOG$V2 == "Cortex_like",]$Orthogroup),
              C = unique(ATH_comOG[ATH_comOG$V2 == "Cortex",]$Orthogroup)
        )

##
com = intersect(intersect(unique(Rice_comOG[Rice_comOG$V2 == "Cortex",]$Orthogroup),  unique(Maize_comOG[Maize_comOG$V2 == "Cortex_like",]$Orthogroup)), unique(ATH_comOG[ATH_comOG$V2 == "Cortex",]$Orthogroup))
saveRDS(com, "/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Data/SHAP_OG_102322_Cortex.RData")
##

#----------------------------
venn = Venn(cortex)
data = process_data(venn, shape_id == "301f")

cortex_plot = ggplot() +
  ggtitle("Cortex") +  
  geom_sf(aes(fill = count), data = venn_region(data)) +
  geom_sf(color = c("purple2","tomato3","orange2"), size = 1, data = venn_setedge(data), show.legend = FALSE) +
  geom_sf_text(label = c("Oryza", "Zeamays", "Arabidopsis"), size = 6, color = c("purple2","tomato3","orange2"), fontface= "bold", data = venn_setlabel(data)) +
  geom_sf_label(aes(label = count), data = venn_region(data), size = 5) +
  scale_fill_gradient(low="white",high =  "green3") +
  theme_void() +
  theme(legend.position="right", 
                  legend.title = element_text(size=12),
                  legend.text = element_text(size=10),
                  plot.title = element_text(size=18, face= "bold", colour= "black", hjust = 0.5),
        )  


#pdf("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Figure/Figure3_SHAP_comparison/SHAP_Venn_Cortex.pdf", width = 7, height = 5)
cortex_plot
#dev.off()
```


```{r}
library(ggVennDiagram)
library(ggplot2)

# List of items
atrichoblast <- list(A = unique(Rice_comOG[Rice_comOG$V2 == "Atrichoblast",]$Orthogroup), 
              B = unique(Maize_comOG[Maize_comOG$V2 == "Epidermis",]$Orthogroup),
              C = unique(ATH_comOG[ATH_comOG$V2 == "Atrichoblast2",]$Orthogroup)
        )

##
com = intersect(intersect(unique(Rice_comOG[Rice_comOG$V2 == "Atrichoblast",]$Orthogroup),   unique(Maize_comOG[Maize_comOG$V2 == "Epidermis",]$Orthogroup)), unique(ATH_comOG[ATH_comOG$V2 == "Atrichoblast2",]$Orthogroup))
saveRDS(com, "/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Data/SHAP_OG_102322_Nonhair.RData")
##

#----------------------------
venn = Venn(atrichoblast)
data = process_data(venn, shape_id == "301f")

atrichoblast_plot = ggplot() +
  ggtitle("Atrichoblast") +  
  geom_sf(aes(fill = count), data = venn_region(data)) +
  geom_sf(color = c("purple2","tomato3","orange2"), size = 1, data = venn_setedge(data), show.legend = FALSE) +
  geom_sf_text(label = c("Oryza", "Zeamays", "Arabidopsis"), size = 6, color = c("purple2","tomato3","orange2"), fontface= "bold", data = venn_setlabel(data)) +
  geom_sf_label(aes(label = count), data = venn_region(data), size = 5) +
  scale_fill_gradient(low="white",high = "#1F9D90D8") +
  theme_void() +
  theme(legend.position="right", 
                  legend.title = element_text(size=12),
                  legend.text = element_text(size=10),
                  plot.title = element_text(size=18, face= "bold", colour= "black", hjust = 0.5),
        )  

#pdf("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Figure/Figure3_SHAP_comparison/SHAP_Venn_Nonhair.pdf", width = 7, height = 5)
atrichoblast_plot
#dev.off()
```


```{r}
library(ggVennDiagram)
library(ggplot2)

# List of items
trichoblast <- list(A = unique(Rice_comOG[Rice_comOG$V2 == "Trichoblast2",]$Orthogroup), 
              B = unique(Maize_comOG[Maize_comOG$V2 == "Epidermis",]$Orthogroup),
              C = unique(ATH_comOG[ATH_comOG$V2 == "Trichoblast2",]$Orthogroup)
        )


##
com = intersect(intersect(unique(Rice_comOG[Rice_comOG$V2 == "Trichoblast2",]$Orthogroup),   unique(Maize_comOG[Maize_comOG$V2 == "Epidermis",]$Orthogroup)), unique(ATH_comOG[ATH_comOG$V2 == "Trichoblast2",]$Orthogroup))
saveRDS(com, "/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Data/SHAP_OG_102322_Hair.RData")
##


#----------------------------
venn = Venn(trichoblast)
data = process_data(venn, shape_id == "301f")

trichoblast_plot = ggplot() +
  ggtitle("Trichoblast") +  
  geom_sf(aes(fill = count), data = venn_region(data)) +
  geom_sf(color = c("purple2","tomato3","orange2"), size = 1, data = venn_setedge(data), show.legend = FALSE) +
  geom_sf_text(label = c("Oryza", "Zeamays", "Arabidopsis"), size = 6, color = c("purple2","tomato3","orange2"), fontface= "bold", data = venn_setlabel(data)) +
  geom_sf_label(aes(label = count), data = venn_region(data), size = 5) +
  scale_fill_gradient(low="white",high = "#5AC863D7") +
  theme_void() +
  theme(legend.position="right", 
                  legend.title = element_text(size=12),
                  legend.text = element_text(size=10),
                  plot.title = element_text(size=18, face= "bold", colour= "black", hjust = 0.5),
        )  

pdf("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Figure/Figure3_SHAP_comparison/SHAP_Venn_Hair.pdf", width = 7, height = 5)
trichoblast_plot
dev.off()
```


```{r}
library(ggVennDiagram)
library(ggplot2)

# List of items
phloem <- list(A = unique(Rice_comOG[Rice_comOG$V2 == "Phloem",]$Orthogroup), 
              B = unique(Maize_comOG[Maize_comOG$V2 == "Phloem",]$Orthogroup),
              C = unique(ATH_comOG[ATH_comOG$V2 == "Phloem",]$Orthogroup)
        )

##
com = intersect(unique(Rice_comOG[Rice_comOG$V2 == "Phloem",]$Orthogroup),unique(ATH_comOG[ATH_comOG$V2 == "Phloem",]$Orthogroup))

com = intersect(intersect(unique(Rice_comOG[Rice_comOG$V2 == "Phloem",]$Orthogroup),  unique(Maize_comOG[Maize_comOG$V2 == "Phloem",]$Orthogroup)), unique(ATH_comOG[ATH_comOG$V2 == "Phloem",]$Orthogroup))
saveRDS(com, "/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Data/SHAP_OG_102322_Phloem.RData")
##

#----------------------------
venn = Venn(phloem)
data = process_data(venn, shape_id == "301f")

phloem_plot = ggplot() +
  ggtitle("Phloem") +  
  geom_sf(aes(fill = count), data = venn_region(data)) +
  geom_sf(color = c("purple2","tomato3","orange2"), size = 1, data = venn_setedge(data), show.legend = FALSE) +
  geom_sf_text(label = c("Oryza", "Zeamays", "Arabidopsis"), size = 6, color = c("purple2","tomato3","orange2"), fontface= "bold", data = venn_setlabel(data)) +
  geom_sf_label(aes(label = count), data = venn_region(data), size = 5) +
  scale_fill_gradient(low="white",high = "tomato") +
  theme_void() +
  theme(legend.position="right", 
                  legend.title = element_text(size=12),
                  legend.text = element_text(size=10),
                  plot.title = element_text(size=18, face= "bold", colour= "black", hjust = 0.5),
        )  


pdf("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Figure/Figure3_SHAP_comparison/SHAP_Venn_Phloem.pdf", width = 7, height = 5)
phloem_plot
dev.off()
```


```{r}
library(ggVennDiagram)
library(ggplot2)

# List of items
stele <- list(A = unique(Rice_comOG[Rice_comOG$V2 == "Stele",]$Orthogroup), 
              B = unique(Maize_comOG[Maize_comOG$V2 == "Stele2",]$Orthogroup),
              C = unique(ATH_comOG[ATH_comOG$V2 == "Stele1",]$Orthogroup)
        )

##
com = intersect(intersect(unique(Rice_comOG[Rice_comOG$V2 == "Stele",]$Orthogroup),  unique(Maize_comOG[Maize_comOG$V2 == "Stele2",]$Orthogroup)), unique(ATH_comOG[ATH_comOG$V2 == "Stele1",]$Orthogroup))
saveRDS(com, "/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Data/SHAP_OG_102322_Stele.RData")
##

#----------------------------
venn = Venn(stele)
data = process_data(venn, shape_id == "301f")

stele_plot = ggplot() +
  ggtitle("Stele") +  
  geom_sf(aes(fill = count), data = venn_region(data)) +
  geom_sf(color = c("purple2","tomato3","orange2"), size = 1, data = venn_setedge(data), show.legend = FALSE) +
  geom_sf_text(label = c("Oryza", "Zeamays", "Arabidopsis"), size = 6, color = c("purple2","tomato3","orange2"), fontface= "bold", data = venn_setlabel(data)) +
  geom_sf_label(aes(label = count), data = venn_region(data), size = 5) +
  scale_fill_gradient(low="white",high = "lightgreen") +
  theme_void() +
  theme(legend.position="right", 
                  legend.title = element_text(size=12),
                  legend.text = element_text(size=10),
                  plot.title = element_text(size=18, face= "bold", colour= "black", hjust = 0.5),
        )  

pdf("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Figure/Figure3_SHAP_comparison/SHAP_Venn_Stele.pdf", width = 7, height = 5)
stele_plot
dev.off()
```

```{r}
library(ggVennDiagram)
library(ggplot2)

# List of items
mix1 <- list(A = unique(Rice_comOG[Rice_comOG$V2 == "Endodermis",]$Orthogroup), 
              B = unique(Maize_comOG[Maize_comOG$V2 == "Endodermal_Initials",]$Orthogroup),
              C = unique(ATH_comOG[ATH_comOG$V2 == "Stele1",]$Orthogroup)
        )

##
com = intersect(intersect(unique(Rice_comOG[Rice_comOG$V2 == "Endodermis",]$Orthogroup), unique(Maize_comOG[Maize_comOG$V2 == "Endodermal_Initials",]$Orthogroup)), unique(ATH_comOG[ATH_comOG$V2 == "Stele1",]$Orthogroup))
#saveRDS(com, "/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Data/SHAP_OG_102322_Endo_Stele.RData")
##

#----------------------------
venn = Venn(mix1)
data = process_data(venn, shape_id == "301f")

mix1_plot = ggplot() +
  ggtitle("Endodermis_SteleATH") +  
  geom_sf(aes(fill = count), data = venn_region(data)) +
  geom_sf(color = c("purple2","tomato3","orange2"), size = 1, data = venn_setedge(data), show.legend = FALSE) +
  geom_sf_text(label = c("Oryza", "Zeamays", "Arabidopsis"), size = 6, color = c("purple2","tomato3","orange2"), fontface= "bold", data = venn_setlabel(data)) +
  geom_sf_label(aes(label = count), data = venn_region(data), size = 5) +
  scale_fill_gradient(low="white",high = "#277F8ECF") +
  theme_void() +
  theme(legend.position="right", 
                  legend.title = element_text(size=12),
                  legend.text = element_text(size=10),
                  plot.title = element_text(size=18, face= "bold", colour= "black", hjust = 0.5),
        )  

pdf("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Figure/Figure3_SHAP_comparison/SHAP_Venn_mix1.pdf", width = 7, height = 5)
mix1_plot
dev.off()
```


```{r}
library(ggVennDiagram)
library(ggplot2)

# List of items
mix2 <- list(A = unique(Rice_comOG[Rice_comOG$V2 == "Endodermis",]$Orthogroup), 
              B = unique(Maize_comOG[Maize_comOG$V2 == "Endodermal_Initials",]$Orthogroup),
              C = unique(ATH_comOG[ATH_comOG$V2 == "Atrichoblast2",]$Orthogroup)
        )

##
com = intersect(intersect(unique(Rice_comOG[Rice_comOG$V2 == "Endodermis",]$Orthogroup),  unique(Maize_comOG[Maize_comOG$V2 == "Endodermal_Initials",]$Orthogroup)), unique(ATH_comOG[ATH_comOG$V2 == "Atrichoblast2",]$Orthogroup))
#saveRDS(com, "/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Data/SHAP_OG_102322_Endo_Nonhair.RData")
##

#----------------------------
venn = Venn(mix2)
data = process_data(venn, shape_id == "301f")

mix2_plot = ggplot() +
  ggtitle("Endodermis_AtrichoblastATH") +  
  geom_sf(aes(fill = count), data = venn_region(data)) +
  geom_sf(color = c("purple2","tomato3","orange2"), size = 1, data = venn_setedge(data), show.legend = FALSE) +
  geom_sf_text(label = c("Oryza", "Zeamays", "Arabidopsis"), size = 6, color = c("purple2","tomato3","orange2"), fontface= "bold", data = venn_setlabel(data)) +
  geom_sf_label(aes(label = count), data = venn_region(data), size = 5) +
  scale_fill_gradient(low="white",high = "#365C8DC7") +
  theme_void() +
  theme(legend.position="right", 
                  legend.title = element_text(size=12),
                  legend.text = element_text(size=10),
                  plot.title = element_text(size=18, face= "bold", colour= "black", hjust = 0.5),
        )  

#pdf("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Figure/Figure3_SHAP_comparison/SHAP_Venn_mix2.pdf", width = 7, height = 5)
mix2_plot
#dev.off()
```




