---
title: "Heatmap to show common OG between cell type of two species shoot dataset"
output:
  html_document: default
  pdf_document: default
date: '2023-04-21'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Clean ortholog find
orthofinder = read.csv("/Users/tranchau/Documents/SC_crossSpecies/MG_scPlantDB/Orthogroups_091023_cleaned.tsv", header = TRUE, sep = "\t")
library(tidyr)
library(dplyr)
library("stringr") 

og_ath = orthofinder[,c("Orthogroup", "Arabidopsis")] %>%
  mutate(Arabidopsis = strsplit(as.character(Arabidopsis), ",")) %>% # Split long string in a row into multiple rows
  unnest(Arabidopsis) %>%
  mutate(Arabidopsis = str_extract(Arabidopsis, "[^.]+"))  %>% # Extract all character before the first dot
  mutate(across(where(is.character), str_trim)) %>%  # Remove white spaces
  distinct(Arabidopsis, .keep_all = TRUE)  # Remove duplicated rows based on Arabidopsis column
  #remove_rownames %>% column_to_rownames(var="Arabidopsis")

og_tom = orthofinder[,c("Orthogroup", "Solanum_lycopersicum")] %>%
  mutate(Solanum_lycopersicum = strsplit(as.character(Solanum_lycopersicum), ",")) %>% # Split long string in a row into multiple rows
  unnest(Solanum_lycopersicum) %>%
  mutate(Solanum_lycopersicum = str_extract(Solanum_lycopersicum, "[^.]+"))  %>% # Extract all character before the first dot
  mutate(across(where(is.character), str_trim)) %>%  # Remove white spaces
  distinct(Solanum_lycopersicum, .keep_all = TRUE)  # Remove duplicated rows based on Solanum column

```


```{r}
# Load Marker Genes
library(Seurat); library(Matrix); library(tidyverse)

#---------------------------------------
MG_ara = readRDS("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/120423_Submission/Figure2/Data/MG_shoot_marker_ATH_05_050323.RData")
print("Number of marker genes per cell types")
table(MG_ara$cluster)


#---------------------------------------
MG_tom = readRDS("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/120423_Submission/Figure2/Data/MG_shoot_marker_Tom_092023.RData")
MG_tom$gene = sub("\\..*", "", MG_tom$gene)
print("Number of marker genes per cell types")
table(MG_tom$cluster)
```

```{r}
# Merge marker gene and OG gene table
# Arabidopsis #######################
Ath_MG_OG = merge(MG_ara, og_ath, by.x = "gene", by.y = "Arabidopsis") %>% arrange( cluster, desc(avg_log2FC)) %>% dplyr:::select("gene", "Orthogroup", "cluster", "avg_log2FC") %>% group_by(cluster) %>% top_n(200)


# Tomato #############################
Tomato_MG_OG = merge(MG_tom, og_tom, by.x = "gene", by.y = "Solanum_lycopersicum") %>% arrange( cluster, desc(avg_log2FC)) %>% dplyr:::select("gene", "Orthogroup", "cluster", "avg_log2FC") %>% group_by(cluster) %>% top_n(200)


## Function create table of common OG gene names between 2 species
count_com_OG = function(Species1, Species2){
  clusters_S1 = unique(Species1$cluster); clusters_S2 = unique(Species2$cluster)
  two_plants <- matrix(nrow=length(clusters_S1), ncol=length(clusters_S2))
  for(i in 1:length(clusters_S1)){
    for(j in 1:length(clusters_S2)){
      list_overlap = intersect(Species1[Species1$cluster == clusters_S1[i],]$Orthogroup, Species2[Species2$cluster == clusters_S2[j],]$Orthogroup)
      num_overlap = length(list_overlap)
    
      two_plants[i,j] = num_overlap
    }
  }
  rownames(two_plants) = unique(Species1$cluster)
  colnames(two_plants) = unique(Species2$cluster) 
  return(two_plants[order(rownames(two_plants)), order(colnames(two_plants))])
}

```


Some clusters are not common cell type between two species. Exclude those clusters to create a better heatmap of common cell type in two species

## Supplement tables which include all clusters.

```{r}
library(ggplot2)
library(reshape)
Ath_MG_OG = subset(Ath_MG_OG, cluster != "Unknown")
df = as.data.frame(count_com_OG(Ath_MG_OG, Tomato_MG_OG))

df$cell_type = rownames(df) # Add column to make 2 variables when using melt function

# Add a row that sums up the values in all other rows
sumrow = df %>% dplyr:::select(-cell_type) %>% colSums() # sum all numeric row in the dataframe
sum_h = c(sumrow, "sum_h") 
df = rbind(df, sum_h) # After merging two data frames, datatype in dataframe will be changed into character
library(hablar)
df = df %>% retype() #%>% as.data.frame(df) # This library and function retype will change the data into the correct type

# Add a column to sum up all values in other columns
df$sum_v = df %>% dplyr:::select(-cell_type) %>% rowSums() # sum all numeric columns in the dataframe
rownames(df) <- df$cell_type  
df

p_value_dataframe = df[1: (nrow(df) - 1), 1: (ncol(df) -2)]
p_value_dataframe
round_p_value_dataframe = p_value_dataframe # Round the p-value to 4 digits to better read the dataframe
conclusionTable_0.001 = p_value_dataframe # Reject the null hypothesis if p-value < 0.05
conclusionTable_0.01 = p_value_dataframe # Reject the null hypothesis if p-value < 0.01
for (i in rownames(p_value_dataframe)){
  for (j in colnames(p_value_dataframe)){
    frame = df[c(i, "sum_h"), c(j, "sum_v")]
    frame[2,2] = frame[2,2] - frame[1,2] - frame[2,1] + frame[1,1]
    frame[1,2] = frame[1,2] - frame[1,1]
    frame[2,1] = frame[2,1] - frame[1,1]
    #print(frame)
    #print(fisher.test(frame)$p.value)
    p_value_dataframe[i,j] = fisher.test(frame, alternative = "greater")$p.value
  }
}


adjusted_pvalue_dataframe <- p_value_dataframe
adjusted_pvalue_dataframe[] = p.adjust(unlist(p_value_dataframe), method = "BH")
conclusionTable_0.001 = ifelse(adjusted_pvalue_dataframe < 0.01, "Reject", "Fail")

table_count = as.matrix(count_com_OG(Ath_MG_OG, Tomato_MG_OG))



#-----
df1 = melt(table_count)
df1$test = melt(conclusionTable_0.001)$value

plot_ATH_Tom_all = ggplot(df1, aes(x = factor(X1, levels = c("Proliferating1", "Proliferating2", "Proliferating3", "Mesophyll1", "Mesophyll2", "Mesophyll3", "Epidermis", "Guard", "Xylem",  "Companion", "Vascular1", "Vascular2", "MZ")), y = factor(X2), fill = value)) +
       geom_tile() + 
       geom_text(aes(label = value), color = "black") +
       scale_fill_gradient(low = "white", high = "darkgreen") +
       geom_rect(data = subset(df1, test == "Reject"), 
            aes(xmin = as.numeric(factor(X1, levels = c("Proliferating1", "Proliferating2", "Proliferating3", "Mesophyll1", "Mesophyll2", "Mesophyll3", "Epidermis", "Guard", "Xylem",  "Companion", "Vascular1", "Vascular2", "MZ"))) - 0.5, 
                xmax = as.numeric(factor(X1, levels = c("Proliferating1", "Proliferating2", "Proliferating3", "Mesophyll1", "Mesophyll2", "Mesophyll3", "Epidermis", "Guard", "Xylem",  "Companion", "Vascular1", "Vascular2", "MZ"))) + 0.5, 
                ymin = as.numeric(X2) + 0.5 , ymax = as.numeric(X2) + 1.5), 
            fill = NA, color = "red", size = 1) +
       theme(legend.position="right", 
                  axis.line.x = element_line(size = 1),
                  axis.line.y = element_line(size = 1),
                  axis.text.x = element_text(color="black", face = "bold",size=13, angle=90, vjust = 0.4, hjust = 1), 
                  axis.text.y = element_text(color="black", face = "bold",size=13, angle=0, vjust = 0.5, hjust = 1),
                  axis.ticks.length = unit(0.1,"cm"),
                  axis.ticks = element_line(size = 1),
                  legend.title = element_text(size=10, face= "bold"),
                  legend.text = element_text(size=8),
                  plot.title = element_text(size=14, face= "bold", colour= "blue", hjust = 0.5),
                  axis.title.x = element_text(size=18, face="bold", colour = "darkgreen", vjust = 1),    
                  axis.title.y = element_text(size=18, face="bold", colour = "darkgreen")) +
  labs(x = "Arabidopsis", y = "Tomato")


plot_ATH_Tom_all


#pdf("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Figure/Shoot_Apex/ATH_Tom_New_092023.pdf", width = 8, height = 6)
plot_ATH_Tom_all
#dev.off()
```

# Extract data from the heatmap
```{r}
## Extract data from the heatmap: based on email 07/19-20/2023
adjusted_pvalue_dataframe$rownames = rownames(adjusted_pvalue_dataframe)
df_adjust_pvalue = melt(adjusted_pvalue_dataframe, id.vars = "rownames")
df1$FDR = df_adjust_pvalue$value
##
Ath_cluster_numOMG = Ath_MG_OG[Ath_MG_OG$cluster %in% c("Proliferating1", "Proliferating2", "Proliferating3", "Mesophyll1", "Mesophyll2", "Mesophyll3", "Epidermis", "Guard", "Xylem",  "Companion", "Vascular1", "Vascular2", "MZ"),] %>%
                      group_by(cluster) %>%
                      summarize(ATH_numOMG = n_distinct(Orthogroup))

Tomato_cluster_numOMG = Tomato_MG_OG %>%
                      group_by(cluster) %>%
                      summarize(Tomato_numOMG = n_distinct(Orthogroup))
##
extractTable = merge(merge(df1, Ath_cluster_numOMG, by.x = "X1", by.y = "cluster"), Tomato_cluster_numOMG, by.x = "X2", by.y = "cluster") 
names(extractTable)[1] = "Tomato_clusters"
names(extractTable)[2] = "ATH_clusters"
names(extractTable)[3] = "comOMG"
extractTable <- extractTable[, c("ATH_clusters", "ATH_numOMG", "Tomato_clusters", "Tomato_numOMG", "comOMG", "FDR", "test")] %>% arrange(FDR)
extractTable

#write.csv(extractTable, "/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/120423_Submission/Figure2/Data/extractTabe_ATH_Tomato_shoot.csv")

```

