---
title: "Heatmap to show common OG between cell type of two species"
output:
  html_document: default
  pdf_document: default
date: '2022-08-04'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Clean ortholog find
orthofinder = read.csv("/Users/tranchau/Documents/SC_crossSpecies/OrthoFinder_source/Ath_maize_tom_rice/OrthoFinder/Results_Aug04/Orthogroups/Orthogroups.tsv", header = TRUE, sep = "\t")

library(tidyr)
library(dplyr)
library("stringr") 

og_ath = orthofinder[,c("Orthogroup", "Arabidopsis")] %>%
  mutate(Arabidopsis = strsplit(as.character(Arabidopsis), ",")) %>% # Split long string in a row into multiple rows
  unnest(Arabidopsis) %>%
  mutate(Arabidopsis = str_extract(Arabidopsis, "[^.]+"))  %>% # Extract all character before the first dot
  mutate(across(where(is.character), str_trim)) %>%  # Remove white spaces
  distinct(Arabidopsis, .keep_all = TRUE)  # Remove duplicated rows based on Arabidopsis column
  #remove_rownames %>% column_to_rownames(var="Arabidopsis")


og_maize = orthofinder[,c("Orthogroup", "Zeamays")] %>%
  mutate(Zeamays = strsplit(as.character(Zeamays), ",")) %>% # Split long string in a row into multiple rows
  unnest(Zeamays) %>%
  mutate(Zeamays = str_extract(Zeamays, "[^_]+")) %>% # Extract all character before the first underscore
  mutate(across(where(is.character), str_trim)) %>% # Remove white spaces
  distinct(Zeamays, .keep_all = TRUE)  # Remove duplicated rows based on Zeamays column
  #remove_rownames %>% column_to_rownames(var="Zeamays")


og_oryza = orthofinder[,c("Orthogroup", "Oryza")] %>%
  mutate(Oryza = strsplit(as.character(Oryza), ",")) %>% # Split long string in a row into multiple rows
  unnest(Oryza) %>%
  mutate(Oryza = str_extract(Oryza, "[^-]+")) %>% # Extract all character before the first underscore
  mutate(across(where(is.character), str_trim)) %>% # Remove white spaces
  distinct(Oryza, .keep_all = TRUE)  %>% # Remove duplicated rows based on Oryza column
  mutate(across('Oryza', str_replace, 't', 'g'))

 og_tom = orthofinder[,c("Orthogroup", "Solanum")] %>%
  mutate(Solanum = strsplit(as.character(Solanum), ",")) %>% # Split long string in a row into multiple rows
  unnest(Solanum) %>%
  mutate(Solanum = str_extract(Solanum, "[^.]+"))  %>% # Extract all character before the first dot
  mutate(across(where(is.character), str_trim)) %>%  # Remove white spaces
  distinct(Solanum, .keep_all = TRUE)  # Remove duplicated rows based on Solanum column
  #remove_rownames %>% column_to_rownames(var="Solanum") 
```



```{r}
ATH_marker = read.table("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Data_SPMarker/111022_ATH_out/opt_SVM_markers_dir/opt_all_novel_marker.txt")
ATH_marker = ATH_marker[-which(ATH_marker$V1 == "feature"),]
ATH_marker$V4 = as.numeric(ATH_marker$V4)

Maize_marker = read.table("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Data_SPMarker/111022_Maize_out/opt_SVM_markers_dir/opt_all_novel_marker.txt")
Maize_marker = Maize_marker[-which(Maize_marker$V1 == "feature"),]
Maize_marker$V4 = as.numeric(Maize_marker$V4)

Rice_marker = read.table("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Data_SPMarker/111022_Rice_out/opt_SVM_markers_dir/opt_all_novel_marker.txt")
Rice_marker = Rice_marker[-which(Rice_marker$V1== "feature"),]
Rice_marker$V4 = as.numeric(Rice_marker$V4)

Tom_marker = read.table("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Data_SPMarker/111022_Tom_out/opt_SVM_markers_dir/opt_all_novel_marker.txt")
Tom_marker = Tom_marker[-which(Tom_marker$V1== "feature"),]
Tom_marker$V4 = as.numeric(Tom_marker$V4)


Ath_MG_OG = merge(ATH_marker, og_ath, by.x = "V1", by.y = "Arabidopsis") %>% arrange(V2, desc(V4)) %>% group_by(V2) %>% slice(1:200)

Maize_MG_OG = merge(Maize_marker, og_maize, by.x = "V1", by.y = "Zeamays") %>% arrange(V2, desc(V4)) %>% group_by(V2) %>% slice(1:200)

Oryza_MG_OG = merge(Rice_marker, og_oryza, by.x = "V1", by.y = "Oryza") %>% arrange(V2, desc(V4)) %>% group_by(V2) %>% slice(1:200)

Tom_MG_OG = merge(Tom_marker, og_tom, by.x = "V1", by.y = "Solanum") %>% arrange(V2, desc(V4)) %>% group_by(V2) %>% slice(1:200)

## Function create table of common OG gene names between 2 species
count_com_OG = function(Species1, Species2){
  clusters_S1 = unique(Species1$V2); clusters_S2 = unique(Species2$V2)
  two_plants <- matrix(nrow=length(clusters_S1), ncol=length(clusters_S2))
  for(i in 1:length(clusters_S1)){
    for(j in 1:length(clusters_S2)){
      list_overlap = intersect(Species1[Species1$V2 == clusters_S1[i],]$Orthogroup, Species2[Species2$V2 == clusters_S2[j],]$Orthogroup)
      num_overlap = length(list_overlap)
    
      two_plants[i,j] = num_overlap
    }
  }
  rownames(two_plants) = unique(Species1$V2)
  colnames(two_plants) = unique(Species2$V2) 
  return(two_plants[order(rownames(two_plants)), order(colnames(two_plants))])
}
```


Some clusters are not common cell type between two species. Exclude those clusters to create a better heatmap of common cell type in two species
```{r}
library(ggplot2)
library(reshape)
df = as.data.frame(count_com_OG(Ath_MG_OG, Oryza_MG_OG))

df$cell_type = rownames(df) # Add column to make 2 variables when using melt function

# Add a row that sums up the values in all other rows
sumrow = df %>% select(-cell_type) %>% colSums() # sum all numeric row in the dataframe
sum_h = c(sumrow, "sum_h") 
df = rbind(df, sum_h) # After merging two data frames, datatype in dataframe will be changed into character
library(hablar)
df = df %>% retype() %>% as.data.frame(df) # This library and function retype will change the data into the correct type

# Add a column to sum up all values in other columns
df$sum_v = df %>% select(-cell_type) %>% rowSums() # sum all numeric columns in the dataframe
rownames(df) <- df$cell_type  
df

p_value_dataframe = df[1: (nrow(df) - 1), 1: (ncol(df) -2)]

for (i in rownames(p_value_dataframe)){
  for (j in colnames(p_value_dataframe)){
    frame = df[c(i, "sum_h"), c(j, "sum_v")]
    frame[2,2] = frame[2,2] - frame[1,2] - frame[2,1] + frame[1,1]
    frame[1,2] = frame[1,2] - frame[1,1]
    frame[2,1] = frame[2,1] - frame[1,1]
    p_value_dataframe[i,j] = fisher.test(frame, alternative = "greater")$p.value
    
  }
}
adjusted_pvalue_dataframe <- p_value_dataframe
adjusted_pvalue_dataframe[] = p.adjust(unlist(p_value_dataframe), method = "BH")
conclusionTable_0.001 = ifelse(adjusted_pvalue_dataframe < 0.01, "Reject", "Fail")
#-----
# This heatmap counts the actual number of common MGs between two species
table_count = as.matrix(count_com_OG(Ath_MG_OG, Oryza_MG_OG))

#-----
df1 = melt(table_count)
df1$test = melt(conclusionTable_0.001)$value
plot_ATH_Rice = ggplot(df1, aes(x = factor(X1, levels = c("Xylem", "Phloem", "Trichoblast1", "Trichoblast2",   "Atrichoblast1",   "Atrichoblast2",  "Stele1",  "Stele2", "Endodermis",  "Cortex","Meristem_Endocortex")), y = factor(X2, levels = c("Xylem", "Phloem",  "Trichoblast1","Trichoblast2",   "Atrichoblast",  "Exodermis",  "Stele", "Endodermis", "Meristem", "Cortex","Cortex_like"  )), fill = value)) +
       geom_tile() + 
       geom_text(aes(label = value), color = "black") +
       scale_fill_gradient(low = "white", high = "royalblue1") +
       geom_rect(data = subset(df1, test == "Reject"), 
            aes(xmin = as.numeric(factor(X1, levels = c("Xylem", "Phloem", "Trichoblast1", "Trichoblast2",   "Atrichoblast1",   "Atrichoblast2",  "Stele1",  "Stele2", "Endodermis",  "Cortex","Meristem_Endocortex"))) - 0.5, xmax = as.numeric(factor(X1, levels = c("Xylem", "Phloem", "Trichoblast1", "Trichoblast2",   "Atrichoblast1",   "Atrichoblast2",  "Stele1",  "Stele2", "Endodermis",  "Cortex","Meristem_Endocortex"))) + 0.5, 
                ymin = as.numeric(factor(X2, levels = c("Xylem", "Phloem",  "Trichoblast1","Trichoblast2",   "Atrichoblast",  "Exodermis",  "Stele", "Endodermis", "Meristem", "Cortex","Cortex_like"  ))) - 0.5, ymax = as.numeric(factor(X2, levels = c("Xylem", "Phloem",  "Trichoblast1","Trichoblast2",   "Atrichoblast",  "Exodermis",  "Stele", "Endodermis", "Meristem", "Cortex","Cortex_like"  ))) + 0.5), 
            fill = NA, color = "yellow1", size = 1) +
       theme(legend.position="right", 
                  axis.line.x = element_line(size = 1),
                  axis.line.y = element_line(size = 1),
                  axis.text.x = element_text(color="black", face = "bold",size=13, angle=90, vjust = 0.4, hjust = 1), 
                  axis.text.y = element_text(color="black", face = "bold",size=13, angle=0, vjust = 0.5, hjust = 1),
                  axis.ticks.length = unit(0.1,"cm"),
                  axis.ticks = element_line(size = 1),
                  legend.title = element_text(size=10, face= "bold"),
                  legend.text = element_text(size=8),
                  plot.title = element_text(size=14, face= "bold", colour= "blue", hjust = 0.5),
                  axis.title.x = element_text(size=18, face="bold", colour = "royalblue1", vjust = 1),    
                  axis.title.y = element_text(size=18, face="bold", colour = "royalblue1")) +
  labs(x = "Arabidopsis", y = "Oryza")


plot_ATH_Rice

```


```{r}
library(ggplot2)
library(reshape)
df = as.data.frame(count_com_OG(Ath_MG_OG, Tom_MG_OG))
df$cell_type = rownames(df) # Add column to make 2 variables when using melt function

# Add a row that sums up the values in all other rows
sumrow = df %>% select(-cell_type) %>% colSums() # sum all numeric row in the dataframe
sum_h = c(sumrow, "sum_h") 
df = rbind(df, sum_h) # After merging two data frames, datatype in dataframe will be changed into character
library(hablar)
df = df %>% retype() %>% as.data.frame(df) # This library and function retype will change the data into the correct type

# Add a column to sum up all values in other columns
df$sum_v = df %>% select(-cell_type) %>% rowSums() # sum all numeric columns in the dataframe
rownames(df) <- df$cell_type  
df

p_value_dataframe = df[1: (nrow(df) - 1), 1: (ncol(df) -2)]

for (i in rownames(p_value_dataframe)){
  for (j in colnames(p_value_dataframe)){
    frame = df[c(i, "sum_h"), c(j, "sum_v")]
    frame[2,2] = frame[2,2] - frame[1,2] - frame[2,1] + frame[1,1]
    frame[1,2] = frame[1,2] - frame[1,1]
    frame[2,1] = frame[2,1] - frame[1,1]
    #print(frame)
    #print(fisher.test(frame)$p.value)
    p_value_dataframe[i,j] = fisher.test(frame, alternative = "greater")$p.value
    
  }
}
adjusted_pvalue_dataframe <- p_value_dataframe
adjusted_pvalue_dataframe[] = p.adjust(unlist(p_value_dataframe), method = "BH")
conclusionTable_0.001 = ifelse(adjusted_pvalue_dataframe < 0.01, "Reject", "Fail")

#-----
table_count = as.matrix(count_com_OG(Ath_MG_OG, Tom_MG_OG))

#-----
df1 = melt(table_count)
df1$test = melt(conclusionTable_0.001)$value
# This heatmap counts the actual number of common MGs between two species
plot_ATH_Tom = ggplot(df1, aes(x = factor(X1, levels = c("Xylem", "Phloem",  "Stele2", "Stele1", "Atrichoblast2", "Atrichoblast1", "Trichoblast1", "Trichoblast2",  "Cortex","Meristem_Endocortex", "Endodermis")), y = factor(X2, levels = c("Xylem", "Phloem1",  "Phloem2", "Vascular1", "Vascular2", "MZ", "Epidermis2", "Epidermis1", "EXO_iCOR1", "EXO_iCOR2", "Exodermis1","Exodermis2")), fill = value)) +
       geom_tile() + 
       geom_text(aes(label = value), color = "black") +
       scale_fill_gradient(low = "white", high = "royalblue1") +
       geom_rect(data = subset(df1, test == "Reject"), 
            aes(xmin = as.numeric(factor(X1, levels = c("Xylem", "Phloem",  "Stele2", "Stele1", "Atrichoblast2", "Atrichoblast1", "Trichoblast1", "Trichoblast2",  "Cortex","Meristem_Endocortex", "Endodermis"))) - 0.5, xmax = as.numeric(factor(X1, levels = c("Xylem", "Phloem",  "Stele2", "Stele1", "Atrichoblast2", "Atrichoblast1", "Trichoblast1", "Trichoblast2",  "Cortex","Meristem_Endocortex", "Endodermis"))) + 0.5, 
                ymin = as.numeric(factor(X2, levels = c("Xylem", "Phloem1",  "Phloem2", "Vascular1", "Vascular2", "MZ", "Epidermis2", "Epidermis1", "EXO_iCOR1", "EXO_iCOR2", "Exodermis1","Exodermis2"))) - 0.5, ymax = as.numeric(factor(X2, levels = c("Xylem", "Phloem1",  "Phloem2", "Vascular1", "Vascular2", "MZ", "Epidermis2", "Epidermis1", "EXO_iCOR1", "EXO_iCOR2", "Exodermis1","Exodermis2"))) + 0.5), 
            fill = NA, color = "yellow1", size = 1) +
       theme(legend.position="right", 
                  axis.line.x = element_line(size = 1),
                  axis.line.y = element_line(size = 1),
                  axis.text.x = element_text(color="black", face = "bold",size=13, angle=90, vjust = 0.4, hjust = 1), 
                  axis.text.y = element_text(color="black", face = "bold",size=13, angle=0, vjust = 0.5, hjust = 1),
                  axis.ticks.length = unit(0.1,"cm"),
                  axis.ticks = element_line(size = 1),
                  legend.title = element_text(size=10, face= "bold"),
                  legend.text = element_text(size=8),
                  plot.title = element_text(size=14, face= "bold", colour= "blue", hjust = 0.5),
                  axis.title.x = element_text(size=18, face="bold", colour = "royalblue1", vjust = 1),    
                  axis.title.y = element_text(size=18, face="bold", colour = "royalblue1")) +
  labs(x = "Arabidopsis", y = "Tomato")

plot_ATH_Tom

```

```{r}
library(ggplot2)
library(reshape)
df = as.data.frame(count_com_OG(Oryza_MG_OG, Tom_MG_OG))
df$cell_type = rownames(df) # Add column to make 2 variables when using melt function

# Add a row that sums up the values in all other rows
sumrow = df %>% select(-cell_type) %>% colSums() # sum all numeric row in the dataframe
sum_h = c(sumrow, "sum_h") 
df = rbind(df, sum_h) # After merging two data frames, datatype in dataframe will be changed into character
library(hablar)
df = df %>% retype() %>% as.data.frame(df) # This library and function retype will change the data into the correct type

# Add a column to sum up all values in other columns
df$sum_v = df %>% select(-cell_type) %>% rowSums() # sum all numeric columns in the dataframe
rownames(df) <- df$cell_type  
df

p_value_dataframe = df[1: (nrow(df) - 1), 1: (ncol(df) -2)]

for (i in rownames(p_value_dataframe)){
  for (j in colnames(p_value_dataframe)){
    frame = df[c(i, "sum_h"), c(j, "sum_v")]
    frame[2,2] = frame[2,2] - frame[1,2] - frame[2,1] + frame[1,1]
    frame[1,2] = frame[1,2] - frame[1,1]
    frame[2,1] = frame[2,1] - frame[1,1]
    p_value_dataframe[i,j] = fisher.test(frame, alternative = "greater")$p.value
    
  }
}
adjusted_pvalue_dataframe <- p_value_dataframe
adjusted_pvalue_dataframe[] = p.adjust(unlist(p_value_dataframe), method = "BH")
conclusionTable_0.001 = ifelse(adjusted_pvalue_dataframe < 0.01, "Reject", "Fail")

#-----
table_count = as.matrix(count_com_OG(Oryza_MG_OG, Tom_MG_OG))

#-----
df1 = melt(table_count)
df1$test = melt(conclusionTable_0.001)$value
# This heatmap counts the actual number of common MGs between two species
plot_Rice_Tom = ggplot(df1, aes(x = factor(X1, levels = c("Xylem", "Phloem", "Meristem", "Trichoblast1", "Trichoblast2", "Atrichoblast",  "Cortex_like", "Cortex", "Exodermis", "Endodermis",  "Stele")), y = factor(X2, levels = c("Xylem", "Phloem1", "Phloem2",  "MZ", "Epidermis1", "Epidermis2", "EXO_iCOR1", "EXO_iCOR2", "Exodermis1", "Exodermis2", "Vascular2" , "Vascular1")), fill = value)) +
       geom_tile() + 
       geom_text(aes(label = value), color = "black") +
       scale_fill_gradient(low = "white", high = "royalblue1") +
       geom_rect(data = subset(df1, test == "Reject"), 
            aes(xmin = as.numeric(factor(X1, levels = c("Xylem", "Phloem", "Meristem", "Trichoblast1", "Trichoblast2", "Atrichoblast",  "Cortex_like", "Cortex", "Exodermis", "Endodermis",  "Stele"))) - 0.5, xmax = as.numeric(factor(X1, levels = c("Xylem", "Phloem", "Meristem", "Trichoblast1", "Trichoblast2", "Atrichoblast",  "Cortex_like", "Cortex", "Exodermis", "Endodermis",  "Stele"))) + 0.5, 
                ymin = as.numeric(factor(X2, levels = c("Xylem", "Phloem1", "Phloem2",  "MZ", "Epidermis1", "Epidermis2", "EXO_iCOR1", "EXO_iCOR2", "Exodermis1", "Exodermis2", "Vascular2" , "Vascular1"))) - 0.5, ymax = as.numeric(factor(X2, levels = c("Xylem", "Phloem1", "Phloem2",  "MZ", "Epidermis1", "Epidermis2", "EXO_iCOR1", "EXO_iCOR2", "Exodermis1", "Exodermis2", "Vascular2" , "Vascular1"))) + 0.5), 
            fill = NA, color = "yellow1", size = 1) +
       theme(legend.position="right", 
                  axis.line.x = element_line(size = 1),
                  axis.line.y = element_line(size = 1),
                  axis.text.x = element_text(color="black", face = "bold",size=13, angle=90, vjust = 0.4, hjust = 1), 
                  axis.text.y = element_text(color="black", face = "bold",size=13, angle=0, vjust = 0.5, hjust = 1),
                  axis.ticks.length = unit(0.1,"cm"),
                  axis.ticks = element_line(size = 1),
                  legend.title = element_text(size=10, face= "bold"),
                  legend.text = element_text(size=8),
                  plot.title = element_text(size=14, face= "bold", colour= "blue", hjust = 0.5),
                  axis.title.x = element_text(size=18, face="bold", colour = "royalblue1", vjust = 1),    
                  axis.title.y = element_text(size=18, face="bold", colour = "royalblue1")) +
  labs(x = "Oryza", y = "Tomato")


plot_Rice_Tom

```



```{r}
library(ggplot2)
library(reshape)
df = as.data.frame(count_com_OG(Ath_MG_OG, Maize_MG_OG))

df$cell_type = rownames(df) # Add column to make 2 variables when using melt function

# Add a row that sums up the values in all other rows
sumrow = df %>% select(-cell_type) %>% colSums() # sum all numeric row in the dataframe
sum_h = c(sumrow, "sum_h") 
df = rbind(df, sum_h) # After merging two data frames, datatype in dataframe will be changed into character
library(hablar)
df = df %>% retype() %>% as.data.frame(df) # This library and function retype will change the data into the correct type

# Add a column to sum up all values in other columns
df$sum_v = df %>% select(-cell_type) %>% rowSums() # sum all numeric columns in the dataframe
rownames(df) <- df$cell_type  
df

p_value_dataframe = df[1: (nrow(df) - 1), 1: (ncol(df) -2)]

for (i in rownames(p_value_dataframe)){
  for (j in colnames(p_value_dataframe)){
    frame = df[c(i, "sum_h"), c(j, "sum_v")]
    frame[2,2] = frame[2,2] - frame[1,2] - frame[2,1] + frame[1,1]
    frame[1,2] = frame[1,2] - frame[1,1]
    frame[2,1] = frame[2,1] - frame[1,1]
    p_value_dataframe[i,j] = fisher.test(frame, alternative = "greater")$p.value
    
  }
}
adjusted_pvalue_dataframe <- p_value_dataframe
adjusted_pvalue_dataframe[] = p.adjust(unlist(p_value_dataframe), method = "BH")
conclusionTable_0.001 = ifelse(adjusted_pvalue_dataframe < 0.05, "Reject", "Fail")
#-----


table_count = as.matrix(count_com_OG(Ath_MG_OG, Maize_MG_OG))

#-----
df1 = melt(table_count)
df1$test = melt(conclusionTable_0.001)$value


plot_ATH_Maize = ggplot(df1, aes(x = factor(X1, levels = c("Xylem","Trichoblast2", "Trichoblast1", "Stele1", "Stele2", "Phloem", "Cortex", "Endodermis",  "Meristem_Endocortex",   "Atrichoblast1", "Atrichoblast2")), y = factor(X2, levels = c("Xylem", "Epidermis", "Stele1","Stele2", "Stele3", "Phloem", "Endodermal_Initials", "Endodermis1", "Endodermis2", "Cortex_like", "Cortex")), fill = value)) +
       geom_tile() + 
       geom_text(aes(label = value), color = "black") +
       scale_fill_gradient(low = "white", high = "royalblue1") +
       geom_rect(data = subset(df1, test == "Reject"), 
            aes(xmin = as.numeric(factor(X1, levels = c("Xylem","Trichoblast2", "Trichoblast1", "Stele1", "Stele2", "Phloem", "Cortex", "Endodermis",  "Meristem_Endocortex",   "Atrichoblast1", "Atrichoblast2"))) - 0.5, xmax = as.numeric(factor(X1, levels = c("Xylem","Trichoblast2", "Trichoblast1", "Stele1", "Stele2", "Phloem", "Cortex", "Endodermis",  "Meristem_Endocortex",   "Atrichoblast1", "Atrichoblast2"))) + 0.5, 
                ymin = as.numeric(factor(X2, levels = c("Xylem", "Epidermis", "Stele1","Stele2", "Stele3", "Phloem", "Endodermal_Initials", "Endodermis1", "Endodermis2", "Cortex_like", "Cortex"))) - 0.5, ymax = as.numeric(factor(X2, levels = c("Xylem", "Epidermis", "Stele1","Stele2", "Stele3", "Phloem", "Endodermal_Initials", "Endodermis1", "Endodermis2", "Cortex_like", "Cortex"))) + 0.5), 
            fill = NA, color = "yellow1", size = 1) +
       theme(legend.position="top", 
                  axis.line.x = element_line(size = 1),
                  axis.line.y = element_line(size = 1),
                  axis.text.x = element_text(color="black", face = "bold",size=13, angle=90, vjust = 0.5, hjust = 1), 
                  axis.text.y = element_text(color="black", face = "bold",size=13, angle=0, vjust = 0.5, hjust = 1),
                  axis.ticks.length = unit(0.1,"cm"),
                  axis.ticks = element_line(size = 1),
                  legend.title = element_text(size=10, face= "bold"),
                  legend.text = element_text(size=8),
                  plot.title = element_text(size=14, face= "bold", colour= "blue", hjust = 0.5),
                  axis.title.x = element_text(size=18, face="bold", colour = "royalblue1", vjust = 10),    
                  axis.title.y = element_text(size=18, face="bold", colour = "royalblue1")) +
  labs(x = "Arabidopsis", y = "Zeamays")



pdf("/Users/tranchau/Documents/SC_crossSpecies/092522_allSteps/Figure/Figure_independentTest/111222_Independent_SVM/030823_ATH_Maize_count.pdf", width = 7, height = 5)
plot_ATH_Maize
dev.off()
```


```{r}
library(ggplot2)
library(reshape)
df = as.data.frame(count_com_OG(Oryza_MG_OG, Maize_MG_OG))
df$cell_type = rownames(df) # Add column to make 2 variables when using melt function

# Add a row that sums up the values in all other rows
sumrow = df %>% select(-cell_type) %>% colSums() # sum all numeric row in the dataframe
sum_h = c(sumrow, "sum_h") 
df = rbind(df, sum_h) # After merging two data frames, datatype in dataframe will be changed into character
library(hablar)
df = df %>% retype() %>% as.data.frame(df) # This library and function retype will change the data into the correct type

# Add a column to sum up all values in other columns
df$sum_v = df %>% select(-cell_type) %>% rowSums() # sum all numeric columns in the dataframe
rownames(df) <- df$cell_type  
df

p_value_dataframe = df[1: (nrow(df) - 1), 1: (ncol(df) -2)]

for (i in rownames(p_value_dataframe)){
  for (j in colnames(p_value_dataframe)){
    frame = df[c(i, "sum_h"), c(j, "sum_v")]
    frame[2,2] = frame[2,2] - frame[1,2] - frame[2,1] + frame[1,1]
    frame[1,2] = frame[1,2] - frame[1,1]
    frame[2,1] = frame[2,1] - frame[1,1]
    #print(frame)
    #print(fisher.test(frame)$p.value)
    p_value_dataframe[i,j] = fisher.test(frame, alternative = "greater")$p.value
    
  }
}
adjusted_pvalue_dataframe <- p_value_dataframe
adjusted_pvalue_dataframe[] = p.adjust(unlist(p_value_dataframe), method = "BH")
conclusionTable_0.001 = ifelse(adjusted_pvalue_dataframe < 0.01, "Reject", "Fail")
table_count = as.matrix(count_com_OG(Oryza_MG_OG, Maize_MG_OG))

#-----
df1 = melt(table_count)
df1$test = melt(conclusionTable_0.001)$value
#-----
plot_Rice_Maize = ggplot(df1, aes(y = factor(X2, levels = c("Xylem","Epidermis",  "Cortex_like", "Cortex", "Endodermal_Initials", "Stele3", "Stele2",  "Stele1", "Phloem", "Endodermis1", "Endodermis2")), x = factor(X1, levels = c("Xylem", "Atrichoblast", "Cortex", "Cortex_like",  "Endodermis","Stele","Phloem", "Meristem", "Trichoblast1", "Trichoblast2", "Exodermis" )), fill = value)) +
       geom_tile() + 
       geom_text(aes(label = value), color = "black") +
       scale_fill_gradient(low = "white", high = "royalblue1") +
       geom_rect(data = subset(df1, test == "Reject"), 
            aes(xmin = as.numeric(factor(X1, levels = c("Xylem", "Atrichoblast", "Cortex", "Cortex_like",  "Endodermis","Stele","Phloem", "Meristem", "Trichoblast1", "Trichoblast2", "Exodermis" ))) - 0.5, xmax = as.numeric(factor(X1, levels = c("Xylem", "Atrichoblast", "Cortex", "Cortex_like",  "Endodermis","Stele","Phloem", "Meristem", "Trichoblast1", "Trichoblast2", "Exodermis" ))) + 0.5, 
                ymin = as.numeric(factor(X2, levels = c("Xylem","Epidermis",  "Cortex_like", "Cortex", "Endodermal_Initials", "Stele3", "Stele2",  "Stele1", "Phloem", "Endodermis1", "Endodermis2"))) - 0.5, ymax = as.numeric(factor(X2, levels = c("Xylem","Epidermis",  "Cortex_like", "Cortex", "Endodermal_Initials", "Stele3", "Stele2",  "Stele1", "Phloem", "Endodermis1", "Endodermis2"))) + 0.5), 
            fill = NA, color = "yellow1", size = 1) +
       theme(legend.position="right", 
                  axis.line.x = element_line(size = 1),
                  axis.line.y = element_line(size = 1),
                  axis.text.x = element_text(color="black", face = "bold",size=13, angle=90, vjust = 0.4, hjust = 1), 
                  axis.text.y = element_text(color="black", face = "bold",size=13, angle=0, vjust = 0.5, hjust = 1),
                  axis.ticks.length = unit(0.1,"cm"),
                  axis.ticks = element_line(size = 1),
                  legend.title = element_text(size=10, face= "bold"),
                  legend.text = element_text(size=8),
                  plot.title = element_text(size=14, face= "bold", colour= "blue", hjust = 0.5),
                  axis.title.x = element_text(size=18, face="bold", colour = "royalblue1", vjust = 1),    
                  axis.title.y = element_text(size=18, face="bold", colour = "royalblue1")) +
  labs(x = "Oryza", y = "Zeamays")


plot_Rice_Maize

```



```{r}
library(ggplot2)
library(reshape)
df = as.data.frame(count_com_OG(Maize_MG_OG, Tom_MG_OG))
df$cell_type = rownames(df) # Add column to make 2 variables when using melt function

# Add a row that sums up the values in all other rows
sumrow = df %>% select(-cell_type) %>% colSums() # sum all numeric row in the dataframe
sum_h = c(sumrow, "sum_h") 
df = rbind(df, sum_h) # After merging two data frames, datatype in dataframe will be changed into character
library(hablar)
df = df %>% retype() %>% as.data.frame(df) # This library and function retype will change the data into the correct type

# Add a column to sum up all values in other columns
df$sum_v = df %>% select(-cell_type) %>% rowSums() # sum all numeric columns in the dataframe
rownames(df) <- df$cell_type  
df

p_value_dataframe = df[1: (nrow(df) - 1), 1: (ncol(df) -2)]

for (i in rownames(p_value_dataframe)){
  for (j in colnames(p_value_dataframe)){
    frame = df[c(i, "sum_h"), c(j, "sum_v")]
    frame[2,2] = frame[2,2] - frame[1,2] - frame[2,1] + frame[1,1]
    frame[1,2] = frame[1,2] - frame[1,1]
    frame[2,1] = frame[2,1] - frame[1,1]
    #print(frame)
    #print(fisher.test(frame)$p.value)
    p_value_dataframe[i,j] = fisher.test(frame, alternative = "greater")$p.value
    
  }
}
adjusted_pvalue_dataframe <- p_value_dataframe
adjusted_pvalue_dataframe[] = p.adjust(unlist(p_value_dataframe), method = "BH")
conclusionTable_0.001 = ifelse(adjusted_pvalue_dataframe < 0.01, "Reject", "Fail")
#-----
table_count = as.matrix(count_com_OG(Maize_MG_OG, Tom_MG_OG))

#-----
df1 = melt(table_count)
df1$test = melt(conclusionTable_0.001)$value

plot_Maize_Tom = ggplot(df1, aes(x =  factor(X1, levels = c("Xylem", "Cortex_like", "Cortex", "Epidermis", "Endodermal_Initials",  "Stele2", "Stele3", "Stele1", "Phloem", "Endodermis1", "Endodermis2")),  y = factor(X2, levels = c("Xylem", "EXO_iCOR1", "EXO_iCOR2", "Epidermis1", "Epidermis2", "MZ", "Exodermis2", "Exodermis1", "Vascular1", "Vascular2", "Phloem1", "Phloem2")), fill = value)) +
       geom_tile() + 
       geom_text(aes(label = value), color = "black") +
       scale_fill_gradient(low = "white", high = "royalblue1") +
       geom_rect(data = subset(df1, test == "Reject"), 
            aes(xmin = as.numeric(factor(X1, levels = c("Xylem","Trichoblast2", "Trichoblast1", "Stele1", "Stele2", "Phloem", "Cortex", "Endodermis",  "Meristem_Endocortex",   "Atrichoblast1", "Atrichoblast2"))) - 0.5, xmax = as.numeric(factor(X1, levels = c("Xylem","Trichoblast2", "Trichoblast1", "Stele1", "Stele2", "Phloem", "Cortex", "Endodermis",  "Meristem_Endocortex",   "Atrichoblast1", "Atrichoblast2"))) + 0.5, 
                ymin = as.numeric(factor(X2, levels = c("Xylem", "Epidermis", "Stele1","Stele2", "Stele3", "Phloem", "Endodermal_Initials", "Endodermis1", "Endodermis2", "Cortex_like", "Cortex"))) - 0.5, ymax = as.numeric(factor(X2, levels = c("Xylem", "Epidermis", "Stele1","Stele2", "Stele3", "Phloem", "Endodermal_Initials", "Endodermis1", "Endodermis2", "Cortex_like", "Cortex"))) + 0.5), 
            fill = NA, color = "yellow1", size = 1) +
       theme(legend.position="right", 
                  axis.line.x = element_line(size = 1),
                  axis.line.y = element_line(size = 1),
                  axis.text.x = element_text(color="black", face = "bold",size=13, angle=90, vjust = 0.4, hjust = 1), 
                  axis.text.y = element_text(color="black", face = "bold",size=13, angle=0, vjust = 0.5, hjust = 1),
                  axis.ticks.length = unit(0.1,"cm"),
                  axis.ticks = element_line(size = 1),
                  legend.title = element_text(size=10, face= "bold"),
                  legend.text = element_text(size=8),
                  plot.title = element_text(size=14, face= "bold", colour= "blue", hjust = 0.5),
                  axis.title.x = element_text(size=18, face="bold", colour = "royalblue1", vjust = 1),    
                  axis.title.y = element_text(size=18, face="bold", colour = "royalblue1")) +
  labs(x = "Zeamays", y = "Tomato")


plot_Maize_Tom

```











